package DBViews;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;

import ConnectionManager.ConnectionManager;

public class DBViews {
	
	static Connection currentCon = null; 
	static ResultSet rs = null; //It is a table of data representing a database result set, generated by executing a statement that queries the database. A ResultSet object maintains a cursor pointing to its current row of data. Initially the cursor is positioned before the first row. The next method moves the cursor to the next row and it returns false when there are no more rows in the ResultSet object
	
	public static ArrayList getCustomerA_number (String username) {
		
		ArrayList <String> a_numberList = new ArrayList <String> ();
		
		Statement stmt = null;
		String customerA_number = "select a_number from ADMINISTRATOR.CUSTOMER_INFO where username='" + username + "'";  //Write the query
		System.out.println("Query: "+ customerA_number);
				
		try {
			//connect to DB 
			
			currentCon = ConnectionManager.getConnection(); 
			stmt=currentCon.createStatement(); 
			rs = stmt.executeQuery(customerA_number); 
			
			 
			 boolean more = rs.next();
			 
			 if (!more) { 
				 System.out.println("Sorry, your don't have any account number"); 
			 } 
			 //if history exists set the isValid variable to true 
			 else { 
				 while (more) {
					 System.out.println("Adding a_numberList");
					 a_numberList.add(rs.getString("a_number"));
					 more = rs.next();
				 }	
				 System.out.println("END WHILE");
			 } 
			
		}
		catch (Exception ex) { 
			 System.out.println("Account failed: An Exception has occurred! " + ex); 
		}
		finally { 
			 if (rs != null) { 
				 try { 
					 rs.close();
				 } 
				 catch (Exception e) {} 
				 rs = null; 
			} 
			if (stmt != null) { 
				try { 
					stmt.close(); 
				} 
				catch (Exception e) {} 
				stmt = null; 
			} 
			if (currentCon != null) { 
				try { 
					currentCon.close(); 
				} 
				catch (Exception e) {} 
				currentCon = null; 
			} 
		 }
		
		for (int i=0; i<a_numberList.size(); i++) System.out.print(a_numberList.get(i) + ", ");
		System.out.println("END FOR");
		return a_numberList;
	}
	
	

}
